# Generated by Django 4.0.4 on 2022-05-23 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellinghub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('U_name', models.CharField(max_length=10)),
                ('U_dob', models.DateField()),
                ('U_username', models.CharField(max_length=30)),
                ('U_password', models.CharField(max_length=20)),
            ],
        ),
    ]
