# Generated by Django 4.0.4 on 2022-06-07 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellinghub', '0002_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('C_status', models.IntegerField()),
                ('C_products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CartProducts', to='sellinghub.products')),
                ('C_users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CartUsers', to='sellinghub.users')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=200)),
                ('address2', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=25)),
                ('city', models.CharField(max_length=25)),
                ('zip', models.IntegerField()),
                ('payment', models.CharField(max_length=15)),
                ('name_card', models.CharField(max_length=40)),
                ('number_card', models.IntegerField()),
                ('exp_card', models.IntegerField()),
                ('cvv_card', models.IntegerField()),
                ('det', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CustomerOrders', to='sellinghub.users')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Purchase_details', models.DateTimeField(auto_now_add=True)),
                ('Order_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OrdersCart', to='sellinghub.cart')),
                ('Order_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OrdersCustomer', to='sellinghub.customer')),
                ('User_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OrdersUsers', to='sellinghub.users')),
            ],
        ),
    ]
