# Generated by Django 4.0.4 on 2022-06-07 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellinghub', '0003_cart_customer_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='Order_number',
            field=models.IntegerField(),
        ),
    ]
