# Generated by Django 4.0.4 on 2022-06-14 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellinghub', '0004_alter_orders_order_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select', models.IntegerField()),
            ],
        ),
    ]
